services:
  db:
    image: postgres:15
    container_name: retail
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: retail
      TZ: Asia/Ho_Chi_Minh # ✅ Fix timezone
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - budget-network

volumes:
  postgres_data:

networks:
  budget-network:
    driver: bridge
