server:
  port: 8080
  servlet:
    context-path: /retailstore

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:      # 👈 Gmail gửi đi
    password:       # 👈 App Password (16 ký tự)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "B8ByAXlvIid7WdrcgVkbvWw9tKkbZ52dvqb9J4KIuQNrdDYrhcLKBf6wEe5mWeTJ"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

logging:
  level:
    org.springframework.security: DEBUG




